{
  "formatVersion": "1.1",
  "component": {
    "group": "com.funny.BottomNavigation",
    "module": "release",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "7iggqvc2rvgopp3lbppoilmnci"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "release-1.1.0.aar",
          "url": "release-1.1.0.aar",
          "size": 48380,
          "sha512": "09a7fdc3f07b6ce4d0194c2625b0b0156580db104dd02b360d273801015cbcace99e33d401b5d64ca833516c42ed81bf7fe5ad4838940293592d157c02bc0274",
          "sha256": "c58a1f0cff756c2f2a671ebd91abfba86b1880b26049e46e16c555cd350f6096",
          "sha1": "1d9e9d463ed5f3a341a726827058d3c2b6fdee5e",
          "md5": "eea192c8c23a3768aedac2c9a1db7aac"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.4.32"
          }
        }
      ],
      "files": [
        {
          "name": "release-1.1.0.aar",
          "url": "release-1.1.0.aar",
          "size": 48380,
          "sha512": "09a7fdc3f07b6ce4d0194c2625b0b0156580db104dd02b360d273801015cbcace99e33d401b5d64ca833516c42ed81bf7fe5ad4838940293592d157c02bc0274",
          "sha256": "c58a1f0cff756c2f2a671ebd91abfba86b1880b26049e46e16c555cd350f6096",
          "sha1": "1d9e9d463ed5f3a341a726827058d3c2b6fdee5e",
          "md5": "eea192c8c23a3768aedac2c9a1db7aac"
        }
      ]
    }
  ]
}
